version: '3.9'

services:
  frontend:
    build: ./frontend
    networks:
      - frontend
    volumes:
      - ./frontend:/app
    ports: 
      - 4200:4200
  api:
    build: ./api
    environment:
      db_username: admin
      db_password: MyLittleSecret
      DB: Connections
      params: "?authSource=admin"
      EXPRESS_PORT: 5000
    networks:
     - frontend
     - backend
    ports:
      - 5000
  servicebus:
    image: nginx:latest
    container_name: servicebus
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
    ports:
     - 8080:80
    depends_on:
      - db 
      - api
      - frontend
    networks: 
      - frontend

  db:
    container_name: db
    image: mongo:latest
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MyLittleSecret
      MONGO_INITDB_DATABASE: Connections
    ports:
      - 27017:27017
    networks:
      - backend

  db-exporter:
    image: bitnami/mongodb-exporter:0.11
    environment:
      - MONGODB_URI=mongodb://db:27017
    restart: always
    ports: 
      - 9216:9216
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - db
      - api
      - frontend
    networks:
      - backend

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - frontend
      - backend

volumes:
  prometheus-data:

networks:
  backend:
  frontend:

    # netwerken
    # data opslag dmv db met volume
    # 