global: 
  scrape_timeout: 10s
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "api"
    dns_sd_configs:
      - names:
        - "API"
        type: "A"
        port: 5000
  - job_name: "db"
    static_configs:
      - targets: ["db-exporter:9216"]
